//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamic_timetable
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInfo
    {
        public int ID { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string ClassCode { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> Week_day { get; set; }
        public Nullable<int> FirstPeriod { get; set; }
        public Nullable<int> NumberOfPeriod { get; set; }
        public string Room { get; set; }
    }
}
