//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamic_timetable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimetableEntities : DbContext
    {
        public TimetableEntities()
            : base("name=TimetableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvancedSearch> AdvancedSearches { get; set; }
        public virtual DbSet<CourseInfo> CourseInfoes { get; set; }
        public virtual DbSet<Link_Path> Link_Path { get; set; }
        public virtual DbSet<OrderOfField> OrderOfFields { get; set; }
    }
}
